course = "    Python programming"
print(course.strip(), "length of string is", len(course.strip()))
print(course.lstrip(), "lstrip")
print(course.rstrip(), "rstrip")
print(course.upper(), "upper")
print(course.lower(), "lower")
print(course.find("Python"), "find")
print("Python" in course, "python is in this course")
print("Python" not in course, "python is not in this course")
print(course.title(), "title")
print(course.capitalize(), "capitalize")
print(course.center(50, "*"), "center")
print(course.startswith("Python"), "startswith")
print(course.endswith("programming"), "endswith")
print(course.split(), "split")
print(course.split(" "), "split with space")
print(course.splitlines(), "splitlines")
print(course.isalnum(), "isalnum")
print(course.isalpha(), "isalpha")
print(course.isdigit(), "isdigit")
print(course.islower(), "islower")
print(course.isupper(), "isupper")
print(course.replace("Python", "Java"), "replace")
print(course.count("Python"), "count")
print(course.index("Python"), "index")
print(course.rindex("Python"), "rindex")
print(course.rjust(50, "*"), "rjust")
print(course.ljust(50, "*"), "ljust")
print(course.zfill(50), "zfill")
print(course.expandtabs(50), "expandtabs")